### ISSUE TITLE
how is a mutual interest determined?

### ISSUE THREAD

**Issue by jeffnv** [jahatch512/OkCoFounder#4]
If it is a super simple process, fine, but if determining matches is complicated I would make this 'matching' process a bonus feature. Maybe just fake it initially by suggesting random potential connections. No one will know the difference and you can change it later (or not).

**Comment by jahatch512** [comment]
Mutual interest will be determined by calculating the number of questions that two users have both answered with the same answer, and dividing this number by the total number of questions (most likely 20).
